/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mourad Fahmi
 */
public class Signup_Patient extends javax.swing.JFrame {

    /**
     * Creates new form Signup_Patient
     */
    
    public boolean checker = true;
    
    public Signup_Patient() {
        initComponents();
    }

    public JTextField getAgePatientTextField() {
        return agePatientTextField;
    }

    public void setAgePatientTextField(JTextField agePatientTextField) {
        this.agePatientTextField = agePatientTextField;
    }

    public JTextField getEmailPatientTextField() {
        return emailPatientTextField;
    }

    public void setEmailPatientTextField(JTextField emailPatientTextField) {
        this.emailPatientTextField = emailPatientTextField;
    }

    public JButton getjButton13() {
        return jButton13;
    }

    public void setjButton13(JButton jButton13) {
        this.jButton13 = jButton13;
    }

    public JTextField getNamePatientTextField() {
        return namePatientTextField;
    }

    public void setNamePatientTextField(JTextField namePatientTextField) {
        this.namePatientTextField = namePatientTextField;
    }

    public JPasswordField getPasswordPatientTextField() {
        return passwordPatientTextField;
    }

    public void setPasswordPatientTextField(JPasswordField passwordPatientTextField) {
        this.passwordPatientTextField = passwordPatientTextField;
    }

    public JTextField getPhonePatientTextField() {
        return phonePatientTextField;
    }

    public void setPhonePatientTextField(JTextField phonePatientTextField) {
        this.phonePatientTextField = phonePatientTextField;
    }

    public JButton getSubmitBnt() {
        return submitBnt;
    }

    public void setSubmitBnt(JButton submitBnt) {
        this.submitBnt = submitBnt;
    }

    public JTextField getUserNamePatientTextField() {
        return userNamePatientTextField;
    }

    public void setUserNamePatientTextField(JTextField userNamePatientTextField) {
        this.userNamePatientTextField = userNamePatientTextField;
    }

    public JTextField getFakePassword() {
        return FakePassword;
    }

    public void setFakePassword(JTextField FakePassword) {
        this.FakePassword = FakePassword;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordPatientTextField = new javax.swing.JPasswordField();
        namePatientTextField = new javax.swing.JTextField();
        submitBnt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userNamePatientTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        agePatientTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        phonePatientTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        emailPatientTextField = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        FakePassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("Please enter the required information");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Password");

        passwordPatientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPatientTextFieldActionPerformed(evt);
            }
        });

        namePatientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namePatientTextFieldActionPerformed(evt);
            }
        });

        submitBnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitBnt.setText("SUBMIT");
        submitBnt.setToolTipText("");
        submitBnt.setFocusable(false);
        submitBnt.setSelected(true);
        submitBnt.setVerifyInputWhenFocusTarget(false);
        submitBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBntActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setText("Patient Account ");

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel5.setText("signup");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Username");

        userNamePatientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNamePatientTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Age");

        agePatientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agePatientTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Phone");

        phonePatientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonePatientTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("E-mail");

        emailPatientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailPatientTextFieldActionPerformed(evt);
            }
        });

        jButton13.setText("BACK");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        FakePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FakePasswordActionPerformed(evt);
            }
        });

        jLabel6.setText("For testing encryption password only:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton13)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FakePassword)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNamePatientTextField)
                                    .addComponent(passwordPatientTextField)))
                            .addComponent(submitBnt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(0, 40, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailPatientTextField)
                                    .addComponent(phonePatientTextField)
                                    .addComponent(namePatientTextField)
                                    .addComponent(agePatientTextField))))
                        .addGap(153, 153, 153))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namePatientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(agePatientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(phonePatientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(emailPatientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(userNamePatientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordPatientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(submitBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FakePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordPatientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPatientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPatientTextFieldActionPerformed

    private void namePatientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namePatientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namePatientTextFieldActionPerformed

    private void userNamePatientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNamePatientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNamePatientTextFieldActionPerformed

    private void agePatientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agePatientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agePatientTextFieldActionPerformed

    private void phonePatientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonePatientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonePatientTextFieldActionPerformed

    private void emailPatientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailPatientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailPatientTextFieldActionPerformed

    private void submitBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBntActionPerformed
        // TODO add your handling code here:
        emailPatientTextField.getText();
        userNamePatientTextField.getText();
        passwordPatientTextField.getPassword();
        if(emailPatientTextField.getText().equals("") || userNamePatientTextField.getText().equals("") || passwordPatientTextField.getPassword().equals("")){
            checker = true;
            JOptionPane.showMessageDialog(null, "Error: fill the all information");
            
        }
        else{
            checker = false;
            JOptionPane.showMessageDialog(null,"Sign Up Successfully");
            //this.setVisible(false);
            Login_Patient login = new Login_Patient();
            login.setVisible(true);  
        }

    }//GEN-LAST:event_submitBntActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        Login_Patient login = new Login_Patient();
        login.setVisible(true);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void FakePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FakePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FakePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FakePassword;
    private javax.swing.JTextField agePatientTextField;
    private javax.swing.JTextField emailPatientTextField;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namePatientTextField;
    private javax.swing.JPasswordField passwordPatientTextField;
    private javax.swing.JTextField phonePatientTextField;
    private javax.swing.JButton submitBnt;
    private javax.swing.JTextField userNamePatientTextField;
    // End of variables declaration//GEN-END:variables
}
